# Generated by Django 4.1.7 on 2023-03-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fruit', max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=10, verbose_name='Цена')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления записи')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('exist', models.BooleanField(default=True, verbose_name='В каталоге?')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
                'ordering': ['name', 'price'],
            },
        ),
    ]
