# Generated by Django 4.1.7 on 2023-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='Кофе', max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
