# Generated by Django 4.1.7 on 2023-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0002_alter_coffee_name_alter_coffee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Общая сумма чека')),
                ('date_printed', models.DateTimeField(auto_now_add=True, verbose_name='Дата распечатки')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['date_printed', 'total_price'],
            },
        ),
    ]
