# Generated by Django 4.1.7 on 2023-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='date_printed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
