# Generated by Django 4.1.7 on 2023-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0004_alter_cheque_date_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
