# Generated by Django 4.1.7 on 2023-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0005_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='desc',
            field=models.TextField(default=1, verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
